name: build
on: [push, pull_request]
jobs:
  test:
    name: Go test ${{ matrix.go }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.15', '1.16', '1.17']
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          git clone --depth=1 https://github.com/${GITHUB_REPOSITORY}
          cd $(basename ${GITHUB_REPOSITORY})
          go build -v -race
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: go get & test
        run: |
          go get -v -t -d ./...
          go test -v ./...